# org: gokaykucuk
# app: trip-shuffler
# NOTE: update this with your service name
service: coronablue-backend

plugins:
  - serverless-offline
  - serverless-plugin-typescript
provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  environment:
    ONESIGNAL_API_KEY: ${env:ONESIGNAL_API_KEY}
    DYNAMODB_TABLE_NAME: coronablue-${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:*"
      Resource:
        - "*"
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  # environment:
  #   - FAUNADB_SERVER_KEY: fnADjzaHdMACAvL_FMnK1O-YL0IB3V62cYnzXjpn
  # NODE_OPTIONS: --mode=production


functions:
  createScanResult:
    handler: src/controllers/ScanResult.CreateScanResult
    events:
      - http:
          path: scan/create
          merhod: post
  createAlert:
    handler: src/controllers/Alert.CreateAlert
    events:
      - http:
          path: scan/create
          merhod: post

resources:
  - ${file(resources/dynamodb-table.yml)}
