# org: gokaykucuk
app: trip-shuffler
# NOTE: update this with your service name
service: trip-shuffler

plugins:
  - serverless-offline
  - serverless-plugin-typescript
provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  environment:
    ONESIGNAL_API_KEY: ${env:ONESIGNAL_API_KEY}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:*"
      Resource:
        - "*"
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  # environment:
  #   - FAUNADB_SERVER_KEY: fnADjzaHdMACAvL_FMnK1O-YL0IB3V62cYnzXjpn
  # NODE_OPTIONS: --mode=production


functions:
  shuffleBot:
    handler: src/shufflebot/bot.Process
    events:
      - sns: tripshuffler-incoming-${opt:stage, 'dev'}
  debug:
    handler: src/mailer/mailer.previewSearchResultsEmail
    events:
      - http:
          path: debug
          method: get
  syncRyanairTrips:
    handler: src/functions/scrapers/trip/ryanairTrips.Sync
  seedAirports:
    handler: src/db/Seeds.SeedAirports
  createCollections:
    handler: src/db/Collections.CreateAll
  dropCollections:
    handler: src/db/Collections.DropAll
  createIndexes:
    handler: src/db/Indexes.CreateAll
